"""initial schema

Revision ID: dd46d8fb0df1
Revises: 
Create Date: 2026-08-15 14:31:53.241872

"""
from alembic import op
import sqlalchemy as sa


revision = 'dd46d8fb0df1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_attempts_ip_at', 'login_attempts', ['ip', 'at'], unique=False)
    op.create_table('monthly_syntheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('overview_es', sa.Text(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('incidents', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('translations_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'month')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('discovered_rss', sa.String(length=1024), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=False),
    sa.Column('mx_zones', sa.JSON(), nullable=True),
    sa.Column('email_briefing', sa.Boolean(), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('lockouts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('gn_url', sa.String(length=2048), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('keyword', sa.String(length=128), nullable=True),
    sa.Column('theme', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['collect_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_articles_url')
    )
    op.create_index('ix_articles_country_fetched', 'articles', ['country', 'fetched_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('title_es', sa.Text(), nullable=False),
    sa.Column('summary_es', sa.Text(), nullable=True),
    sa.Column('recommendations_es', sa.JSON(), nullable=True),
    sa.Column('summary_version', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=16), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recurrence', sa.Integer(), nullable=False),
    sa.Column('independent_sources', sa.Integer(), nullable=False),
    sa.Column('has_state_media', sa.Boolean(), nullable=False),
    sa.Column('score_detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['collect_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_events_dedup_key')
    )
    op.create_index('ix_events_country_occurred', 'events', ['country', 'occurred_at'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('web_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('event_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'article_id')
    )
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'lang')
    )
    op.create_table('weekly_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('theme', sa.String(length=32), nullable=False),
    sa.Column('iso_week', sa.String(length=10), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('mini_summary_es', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['collect_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'theme')
    )
    op.create_index('ix_weekly_country_week', 'weekly_items', ['country', 'iso_week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weekly_country_week', table_name='weekly_items')
    op.drop_table('weekly_items')
    op.drop_table('translations')
    op.drop_table('event_articles')
    op.drop_table('web_sessions')
    op.drop_table('password_resets')
    op.drop_table('invitations')
    op.drop_index('ix_events_country_occurred', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_articles_country_fetched', table_name='articles')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('monthly_syntheses')
    op.drop_index('ix_login_attempts_ip_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('collect_runs')
    # ### end Alembic commands ###
